language: generic
before_install:
- chmod +x build.sh
install:
script:
  - "./build.sh"
deploy:
  api_key:
    secure: DFDUgB0D4J50k8t4pAVZYWXJpdPo7yTtZfCTloo5cz/ALQT+nn7weLdtOyqpcOeUw6DZtacqTXH4Bgo4v22BmwIKGTiSuNqG7MVR4Ffb5eVpqqKvxQufz6dP0siYhAiheBGMnGFbcbIn5fS+FSNdQLlgetg8b7z3sBoMonaRtqH2SMYVLvq2xktq9Sihkmyj6NdA3mNLRfZzuS6+v/hXDOoIHQRmxnGoDXW3HemWFTJcuQ8MMi6HsHU5gQ1L3jv7Ik0k9h1qg0JIx4nWMTkWqR3GATAf0VdXNAVu/sdmv7ZKnL0cl5UDHksm3Xie06bvJigP7gzHka9JZf1g4FN3mOCyDXF4EVGp2iItoj7cPNxt7yIA1cxVYKZ6gZ0rY3OFSU1DBQr66nrjN8dBpwlfGBqWtHYj6NFgcuiMnfmVN++V2snPiFhSgfHYXoG5u/EhdThDxozvwzbxymUEUt71t0UlruKpaeRkmVJ3YcWvDS96nY3rvZKRV2YhxyNtKZ28GNQwMXj94wUmgrukWmbp/GMtTCCScfelnRSjPddudLUf3GSXAHF9AtfpO44zHaMi8naByGNCrwblHOwube8DLMbyZLi/ocvmkNwsRWxDzOPhEK34NdFzMCAn4qrtOLuJuf010ljd2qlbpe4jXiqXPQVts3KdQikBWd1gmJh9uR8=
