language: generic
before_install:
- chmod +x build.sh
install: 
script:
- "./build.sh"
deploy:
  api_key:
    secure: DFDUgB0D4J50k8t4pAVZYWXJpdPo7yTtZfCTloo5cz/ALQT+nn7weLdtOyqpcOeUw6DZtacqTXH4Bgo4v22BmwIKGTiSuNqG7MVR4Ffb5eVpqqKvxQufz6dP0siYhAiheBGMnGFbcbIn5fS+FSNdQLlgetg8b7z3sBoMonaRtqH2SMYVLvq2xktq9Sihkmyj6NdA3mNLRfZzuS6+v/hXDOoIHQRmxnGoDXW3HemWFTJcuQ8MMi6HsHU5gQ1L3jv7Ik0k9h1qg0JIx4nWMTkWqR3GATAf0VdXNAVu/sdmv7ZKnL0cl5UDHksm3Xie06bvJigP7gzHka9JZf1g4FN3mOCyDXF4EVGp2iItoj7cPNxt7yIA1cxVYKZ6gZ0rY3OFSU1DBQr66nrjN8dBpwlfGBqWtHYj6NFgcuiMnfmVN++V2snPiFhSgfHYXoG5u/EhdThDxozvwzbxymUEUt71t0UlruKpaeRkmVJ3YcWvDS96nY3rvZKRV2YhxyNtKZ28GNQwMXj94wUmgrukWmbp/GMtTCCScfelnRSjPddudLUf3GSXAHF9AtfpO44zHaMi8naByGNCrwblHOwube8DLMbyZLi/ocvmkNwsRWxDzOPhEK34NdFzMCAn4qrtOLuJuf010ljd2qlbpe4jXiqXPQVts3KdQikBWd1gmJh9uR8=
env:
  global:
    secure: FDUhYGZlqhnvLjhtJg1KUnzdOdshIFbnHgRoBh05pDSjU6i0liG+MoEfbCU5BJNG6jU0P7HW0WXt71vjZwK7uQUzzfNSNMc+Nd2jROID2OD/jxCTwS42tyIp4K2wcJdoiycpL+mfukG7076xGsghyNPGt4MghnEITvkbBa2DMvF6sExdiXwaC6+QDbXIRbjU4Br9yYUoaBoR9zQRUYuQ5Jfo2wX4+CLkV7tbffWoC3/JTenDUUtMBM97o+xVrhdz2scb+z0UAghOUTMbNlnmpfCk1iJOLS0tBUH0srAr3Gjv0MP3bDYm6PSdW6Di/EzzcObRJS/VB2XNpJabdmwOwjUINjZOsCHp4hIH7S5VsoLYN+Cc6Qi1S4KHDZ/I5ikS36KhB/AGirg1iImrLH2+1ApFdxmaMGFfLlwchdUHdBmg8C6f2ZnouAN+L9hnrdFizSzZY50dcaSWSEpzbnvff1JK39Ig5nC5KDmjdHd9NydZWS9w8PtZoat/9US1viYCEBggn4bXXeBvCkLLM5NL6Kq7t9aVS6cCEohlZIsGMwBv0y81sjZCBKj0Wnz/3LhSAj6SY0w9Hmy6Q2ik4HP5sftBgb34hdj7XsXUL36mWHryizQ2fJ9qJVrJpvUm+CogMqJFs+DInGMqdHrCva1dsn6XSxV+SvJlH+WjEOLpBYQ=
